<?php

/**
 * @file
 * Contains jumplink.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function jumplink_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the jumplink module.
    case 'help.page.jumplink':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A Drupal 8 Module which allows editors to create jump links without needing to set classes and anchors.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function jumplink_theme($existing, $type, $theme, $path) {
  return array(
    'jumplinks' => array(
      'template' => 'block--jumplinks',
      'variables' => array(
        'jumplinks' => NULL,
      ),
    )
  );
}

/**
 * Implements hook_preprocess_paragraph().
 */
function jumplink_preprocess_paragraph(&$variables) {
  // Adding an ID attribute to all paragraphs so the jump links have something
  // to actually link to.
  $pid = $variables['paragraph']->id();
  $variables['attributes']['id'] = 'paragraph-' . $pid;
}
